### ISSUE TITLE
Server side rendering with universal

### ISSUE THREAD

**Issue by divya130** [skynet2/ngx-google-places-autocomplete#19]
I get the following error:

C:\xampp\htdocs\travelbuddhi-ng5\node_modules\ngx-google-places-autocomplete\ngx
-google-places-autocomplete.directive.js:1
(function (exports, require, module, __filename, __dirname) { import { Directive
, ElementRef, EventEmitter, Input, NgZone, Output } from '@angular/core';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.mvfG (C:\xampp\htdocs\travelbuddhi-ng5\dist-server\main.bundle.js:
1:1838418)

**Comment by jkapongo** [comment]
@divya130 I think the [solution I provided ](https://github.com/skynet2/ngx-google-places-autocomplete/issues/15#issuecomment-465371214) for Issue #15 can be helpful to you as well.

**Comment by mshenawy** [comment]
> @divya130 I think the [solution I provided ](https://github.com/skynet2/ngx-google-places-autocomplete/issues/15#issuecomment-465371214) for Issue #15 can be helpful to you as well.

this solution didn't work with me, I'm using angular 8 and keep receiving this error:( 
ng2-tel-input.js:24
import { Directive, ElementRef, EventEmitter, HostListener, Inject, Input, Output, PLATFORM_ID } from '@angular/core';
       ^

SyntaxError: Unexpected token {
SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:720:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
